name: Create .love file and build to .exe

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create-love:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install zip utility
      run: sudo apt-get install zip -y

    - name: Create .love file
      run: |
        zip -r game.love *
        mv game.love ${GITHUB_REPOSITORY#*/}-$(date +%Y%m%d%H%M%S).love

    - name: Upload .love file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: .LOVE file
        path: |
          *.love

  convert-love:
    runs-on: ubuntu-latest
    needs: create-love

    steps:
    - name: Download .love file from previous job
      uses: actions/download-artifact@v2
      with:
        name: .LOVE file
        path: .

    - name: Install zip utility
      run: sudo apt-get install zip -y

    - name: Download LOVE.exe
      run: |
        mkdir love
        cd love
        curl -L -o love-win.zip https://github.com/love2d/love/releases/download/11.5/love-11.5-win64.zip
        unzip love-win.zip
        mv love-11.5-win64/* .
        cd ..

    - name: Create .exe file
      run: |
        cp love/love.exe game.exe
        cat ${GITHUB_REPOSITORY#*/}-*.love >> game.exe
        cp love/*.dll .

    - name: Upload .exe file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: Game Build
        path: |
          game.exe
          *.dll